# Generated by Django 2.2.17 on 2020-12-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name_plural': 'wishes'},
        ),
    ]
