# Generated by Django 2.2.17 on 2020-12-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
    ]
