# Generated by Django 2.2.17 on 2020-12-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name_plural': 'wishes'},
        ),
    ]
