# Generated by Django 2.2.17 on 2020-12-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplants', '0002_auto_20201201_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={},
        ),
    ]
